#!/bin/bash

g++ $(find src components -name "*.cpp") \
    $(find lib -name "*.cpp" 2>/dev/null) \
    -Icomponents \
    -Icomponents/circle \
    -Icomponents/gameObject \
    -Icomponents/rectangle \
    -Icomponents/transform \
    -o run \
    -lraylib -lm -lpthread -ldl -lX11

if [ $? -eq 0 ]; then
    ./run
fi
